### ISSUE TITLE
How to specify custom config

### ISSUE THREAD

**Issue by bd8392** [Tob1asDocker/rpi-mariadb#3]
Hi :-) I plan to use your image for my pi4 :-). Is it based on the official-one? How can I specify a custom-config with your Image?

**Comment by Tob1as** [comment]
Hi,

This is based on the official images as much as possible. Of MariaDB there are unfortunately no official packages for ARM 32bit on the package mirror and so I have to use the versions that are available in the operating system...

Folder-Paths:
* ubuntu/debian: `/etc/mysql/conf.d/`
* alpine: `/etc/my.cnf.d/`

Example for ubuntu:
`-v $(pwd)/mydbconfig.cnf:/etc/mysql/conf.d/mydbconfig.cnf`

If you use 64bit ARM OS you can use the offical Images. ;)

**Comment by bd8392** [comment]
really cool thank you =) I'm gonna test it =)

**Comment by bd8392** [comment]
Works like a charm =) Thank you =)
